steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/cloud-run-011/cloudrun:$COMMIT_SHA', '.']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/cloud-run-011/cloudrun:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'engine', '--region=us-central1', '--platform=managed', '--image=gcr.io/app-engine-011/engine:$COMMIT_SHA']
